"""
sidecar/agent/self_improvement.py — Gap catcher, log.md appender, raw/drafts generator (v0.4)

Jika LLM menjawab "Not available in source" atau sufficiency_gate menandai gap,
agent mencatat ke wiki/log.md dan membuat draf di raw/drafts/ untuk Human-in-the-Loop review.

Dipanggil setelah LLM response, bukan sebelum.
"""
from __future__ import annotations
import re
from pathlib import Path
from datetime import datetime

VAULT_ROOT = Path("C:/Users/PC/Documents/Obsidian/Dika/wiki")
LOG_PATH = VAULT_ROOT / "log.md"
DRAFTS_DIR = Path("C:/Users/PC/Documents/Obsidian/Dika/raw/drafts")

GAP_PATTERNS = [
    r"not available in source",
    r"tidak ada di (konteks|vault|sumber)",
    r"threshold.*tidak ditemukan",
    r"gap.*vault",
]

def _is_gap_response(llm_text: str, sufficiency_result: dict | None = None) -> bool:
    if sufficiency_result and sufficiency_result.get("gap"):
        return True
    low = (llm_text or "").lower()
    return any(re.search(p, low) for p in GAP_PATTERNS)

def _slugify(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s[:48] or "gap-draft"

def capture_gap(
    query: str,
    llm_text: str = "",
    sufficiency_result: dict | None = None,
    vault_hits: list | None = None,
    file_name: str = "",
) -> dict:
    """
    Cek apakah ada gap; jika ya, append ke log.md dan buat draft di raw/drafts/.

    Returns: {"gap": bool, "log_appended": bool, "draft_path": str|None}
    """
    if not _is_gap_response(llm_text, sufficiency_result):
        return {"gap": False, "log_appended": False, "draft_path": None}

    # infer topic
    topic = (sufficiency_result or {}).get("missing") or "threshold/SOP tidak ditemukan"
    # try extract requested KPI from query
    kpi_match = re.search(r"\b(rsrp|rsrq|sinr|rssi|cqi|mcs|prb|pci|earfcn|throughput|handover)\b", query.lower())
    if kpi_match:
        topic = f"{kpi_match.group(1).upper()} — {topic}"

    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")

    # 1) append to log.md
    log_ok = False
    try:
        VAULT_ROOT.mkdir(parents=True, exist_ok=True)
        entry = (
            f"\n## [{date_str} {time_str}] gap | {topic}\n"
            f"- Query: \"{query[:200]}\"\n"
            f"- Missing: {topic}\n"
            f"- File: {file_name or '-'}\n"
            f"- LLM hint: {(llm_text or '')[:200].replace(chr(10), ' ')}\n"
            f"- Action: draft created in raw/drafts/\n"
        )
        with open(LOG_PATH, "a", encoding="utf-8") as f:
            f.write(entry)
        log_ok = True
    except Exception as e:
        print(f"self_improvement log append failed: {e}")

    # 2) create draft in raw/drafts/
    draft_path = None
    try:
        DRAFTS_DIR.mkdir(parents=True, exist_ok=True)
        slug = _slugify(topic)
        draft_file = DRAFTS_DIR / f"{date_str}-{slug}.md"
        # avoid overwrite
        if draft_file.exists():
            draft_file = DRAFTS_DIR / f"{date_str}-{slug}-{now.strftime('%H%M%S')}.md"
        draft_content = f"""---
title: "{topic}"
type: "draft-note"
status: "draft"
created: "{date_str}"
query: "{query[:200]}"
missing: "{topic}"
source_file: "{file_name}"
---

# {topic} — Draft (Human Review Required)

> Auto-generated by RF-Copilot v0.4 Self-Improvement Loop pada {date_str} {time_str}.
> Engineer: lengkapi threshold/SOP lalu pindahkan ke `wiki/atomic/` atau `wiki/synthesis/` setelah review.

## Context
- Query user: `{query[:400]}`
- LLM response snippet: `{(llm_text or '')[:400].replace(chr(10), ' ')}`
- Vault hits: {len(vault_hits or [])} (tidak ada konteks relevan)

## TODO (Engineer)
- [ ] Isi definisi / threshold / formula yang benar (jangan halusinasi)
- [ ] Tambah `tags`, `domain`, `related` dan `[[Wikilinks]]`
- [ ] Pindahkan ke `wiki/atomic/<kebab>.md` dengan frontmatter lengkap
- [ ] Update `wiki/index.md` dan hapus draft ini atau arsipkan

## Source
- Not available in source. (isi manual)
"""
        draft_file.write_text(draft_content, encoding="utf-8")
        draft_path = str(draft_file)
    except Exception as e:
        print(f"self_improvement draft failed: {e}")

    return {"gap": True, "log_appended": log_ok, "draft_path": draft_path}
